name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Slither
        run: |
          pip install slither-analyzer
          
      - name: Run Slither
        run: |
          mkdir -p analysis_output
          slither . > documents/slither_report.md

      - name: Commit Slither Report
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add documents/slither_report.md
          git commit -m "Add Slither analysis report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
